package_info:
  id: {{cookiecutter.package_id}}
  name: {{cookiecutter.package_name}}
  description: {{cookiecutter.package_desc}}
  author: {{cookiecutter.author}}
  repo: # fill this in with a link to the git repo
  version: 0.0.1

fprime_info:
  built-with: << GET F PRIME VERSION >>
  compatible-with:
    - << GET F PRIME VERSION >> 

dependencies:
  # some dependencies, if had
