name: Format Python

on: [push, pull_request]
jobs:
  format:
      name: Format
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Check formatting
        run: |
          pip install click==8.0.4 black==21.6b0
          black --check --diff ./
